version: "3"

services:
  db:
    image: 547369544921.dkr.ecr.eu-central-1.amazonaws.com/psql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=test
  typesense:
      image: 547369544921.dkr.ecr.eu-central-1.amazonaws.com/typesense
      volumes:
        - typesense_data:/data
      ports:
        - "40:40"
      environment:
        - TYPESENSE_DATA_DIR=/data
        - TYPESENSE_API_KEY=abcd
        - TYPESENSE_ENABLE_CORS=True
        - TYPESENSE_API_PORT=40
  web:
    image: 547369544921.dkr.ecr.eu-central-1.amazonaws.com/typesense
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    volumes:
      - "~/typesense_orm:/typesense_orm:ro"
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql+asyncpg://developer:testpassword@db:5432/test
      - TYPESENSE_URL=http://typesense:40
    depends_on:
      - db
      - typesense

volumes:
  postgres_data:
  typesense_data:
